# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'form.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import sqlite3

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QApplication, QWidget, QTableWidgetItem, QMainWindow, QGridLayout


def query(customerName,province,city,matterCode,matterDes):
    data=[]
    conn = sqlite3.connect('./sqlite3/xinwei.db')
    cursor = conn.cursor()
    print('hahaha')
    cursor = cursor.execute(f"SELECT *  from info where customerName like'%{customerName}%' and province like '%{province}%'and city like '%{city}%' and mattercode like '%{matterCode}%' and matterDes like '%{matterDes}%'")
    for row in cursor:
        data.append(row)
    return data


class Ui_Form(QMainWindow):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1440, 900)
        self.tableWidget = QtWidgets.QTableWidget(Form)
        self.tableWidget.setGeometry(QtCore.QRect(0, 90, 1440, 800))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(10)
        self.tableWidget.setRowCount(1000)
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(890, 60, 80, 30))
        self.pushButton.setObjectName("pushButton")
        self.pushButton.clicked.connect(self.buttonClicked)
        self.label_6 = QtWidgets.QLabel(Form)
        self.label_6.setGeometry(QtCore.QRect(270, 10, 431, 51))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(22)
        font.setBold(True)
        self.label_6.setFont(font)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.widget = QtWidgets.QWidget(Form)
        self.widget.setGeometry(QtCore.QRect(0, 60, 832, 30))
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.lineEdit = QtWidgets.QLineEdit(self.widget)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout.addWidget(self.lineEdit)
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.horizontalLayout.addWidget(self.lineEdit_2)
        self.label_3 = QtWidgets.QLabel(self.widget)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.label_3)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.horizontalLayout.addWidget(self.lineEdit_3)
        self.label_4 = QtWidgets.QLabel(self.widget)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout.addWidget(self.label_4)
        self.lineEdit_4 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.horizontalLayout.addWidget(self.lineEdit_4)
        self.label_5 = QtWidgets.QLabel(self.widget)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout.addWidget(self.label_5)
        self.lineEdit_5 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.horizontalLayout.addWidget(self.lineEdit_5)
        self.retranslateUi(Form)
        grid = QGridLayout()
        grid.setSpacing(10)

        grid.addWidget(self.label_6, 1, 0)

        grid.addWidget(self.pushButton, 2, 1)

        grid.addWidget(self.tableWidget, 3, 0)

        Form.setLayout(grid)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.pushButton.setText(_translate("Form", "查询"))
        self.label_6.setText(_translate("Form", "新威数据查询"))
        self.label.setText(_translate("Form", "客户名称"))
        self.label_2.setText(_translate("Form", "省份"))
        self.label_3.setText(_translate("Form", "地市"))
        self.label_4.setText(_translate("Form", "型号"))
        self.label_5.setText(_translate("Form", "描述"))

    def buttonClicked(self):
        self.tableWidget.clear()
        customerName=self.lineEdit.text()
        province = self.lineEdit_2.text()
        city = self.lineEdit_3.text()
        matterCode = self.lineEdit_4.text()
        matterDes = self.lineEdit_5.text()
        print(customerName,province,city,matterCode,)
        data=query(customerName,province,city,matterCode,matterDes)
        print(data)
        row=len(data)
        col=len(data[0])
        for i in range(row):
            for j in range(col):
                temp=str(data[i][j])
                dat=QTableWidgetItem(temp)
                self.tableWidget.setItem(i,j,dat)

app = QApplication([])
window = QWidget()
ui=Ui_Form()
ui.setupUi(window)
window.show()
app.exec_()